name: dart_gen
description: Generate dart codes from graphql ast.
version: 0.1.0
homepage: https://github.com/Brooooooklyn/graphql_codegen
author: LongYinan <lynweklm@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  graphql_ast_visitor: ^0.1.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

dependency_overrides:
  graphql_ast_visitor:
    path: ../graphql_ast_visitor