name: graphql_codegen
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: LongYinan <lynweklm@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.4.1
  graphql_parser: ^1.1.3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
